# 데이터 탐색

판다스 데이터프레임의 `info()`, `describe()` 등의 메서드를 활용하여 데이터프레임의 기초 정보와 통계량을 파악하는 방법을 다룬다.
또한 특성의 자료형에 따라 수치형, 범주형, 이산형, 연속형으로 구분하고,
인덱싱과 슬라이싱을 통해 원하는 데이터를 선택하는 방법을 소개한다.

**기본 설정**

`numpy`와 `pandas` 라이브러리를 각각 `np`와 `pd`로 불러온다.

In [1]:
import numpy as np
import pandas as pd

**데이터 저장소**

In [2]:
data_url = 'https://raw.githubusercontent.com/codingalzi/code-workout-datasci/refs/heads/master/data/'

## 승촌보 데이터셋

### 데이터 기초 정보

기본 데이터 저장소에 있는 `sc_weir.csv` 파일은
영산강에 설치된 승촌보에서 측정된 두 종류의 데이터를 담고 있다.

- `Chl-a`: 녹조 발생의 주요 요인인 클로로필-A의 수치 100개
- `Discharge`: 보에서 방출되는 시간당 방류량 수치 100개

In [3]:
sc_weir_df = pd.read_csv(data_url+'sc_weir.csv')

sc_weir_df

    Chl-a  Discharge
0      51         25
1      51         25
2      53         24
3      53         24
4      54         22
..    ...        ...
95    122          9
96    122          9
97    124         49
98    125          9
99    124          9

[100 rows x 2 columns]

**데이터 수집 목적**

클로로필-A 농도가 높을 수록 수질(water quality)이 나쁘다고 판정하는데
방류량이 많을 수록 클로로필-A 농도는 일반적으로 올라간다.
승촌보 데이터셋은 수질과 방류량 사이의 상관관계를 확인하기 위해 수집되었다.

**승촌보 지리 정보**

영산강은 광주광역시에서부터 전라남도 나주를 거쳐 서해로 흘러 들어간다. 
영산강에 4대강 사업으로 승촌보와 죽산보 두 개의 보가 설치되었으며
승촌보는 광주광역시 남구에 위치해서 광주 도심에서 매우 가깝다.
데이터는 승촌보 상류 지역에서 수집된 데이터의 일부이다.

<div align="center">
    <img src="https://raw.githubusercontent.com/codingalzi/code-workout-datasci/master/images/sc-weir.png" width="800">
</div>

**데이터셋 크기**

데이터프레임의 `shape` 속성을 확인하여 데이터셋의 크기를 확인한다.

In [4]:
sc_weir_df.shape

(100, 2)

**특성별 기초 정보 확인**

데이터프레임의 `info()` 메서드는 특성별(열별) 데이터 개수와 `dtype`을 확인해준다.
승촌보 데이터셋의 경우 `Chl-a`와 `Discharge` 두 개의 특성을 포함하며,
두 특성 모두 정수값으로 구성되어 있다.
그리고 특성별 데이터 수는 각각 100개이다.

In [5]:
sc_weir_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Chl-a      100 non-null    int64
 1   Discharge  100 non-null    int64
dtypes: int64(2)
memory usage: 1.7 KB

**특성 종류**

데이터셋에 포함된 특성들의 목록은 `columns` 속성으로도 확인된다.

In [6]:
sc_weir_df.columns

Index(['Chl-a', 'Discharge'], dtype='str')

### 특성 분포

In [7]:
sc_weir_df.describe()

           Chl-a  Discharge
count  100.00000  100.00000
mean    93.86000   14.93000
std     22.62564    6.37903
min     51.00000    9.00000
25%     74.50000   11.00000
50%     98.00000   13.00000
75%    114.50000   16.00000
max    125.00000   52.00000

(2) 가장 높은 클로로필-A의 수치는 얼마인가?

답:

`describe()` 메서드를 실행하면 각 특성별 데이터의 분포를 보여준다.
그중에 최댓값도 맨 아랫줄에 언급된다.
클로로필-A 수치의 최댓값은 125.0이다.

In [10]:
sc_weir_df.describe()

           Chl-a  Discharge
count  100.00000  100.00000
mean    93.86000   14.93000
std     22.62564    6.37903
min     51.00000    9.00000
25%     74.50000   11.00000
50%     98.00000   13.00000
75%    114.50000   16.00000
max    125.00000   52.00000

그런데 `describe()` 메서드의 반환값 또한 데이터프레임 객체다.
따라서 최댓값을 인덱싱으로 확인할 수도 있다.

In [11]:
desc = sc_weir_df.describe()
desc

           Chl-a  Discharge
count  100.00000  100.00000
mean    93.86000   14.93000
std     22.62564    6.37903
min     51.00000    9.00000
25%     74.50000   11.00000
50%     98.00000   13.00000
75%    114.50000   16.00000
max    125.00000   52.00000

- 데이터에 포함된 두 특성의 최댓값 확인(반환값은 시리즈 객체)

In [12]:
desc.loc['max']

Chl-a        125.0
Discharge     52.0
Name: max, dtype: float64

- 클로로필-A의 최댓값 확인

In [13]:
desc.loc['max', 'Chl-a']

np.float64(125.0)

(3) 가장 낮은 시간당 방류량 수치는 얼마인가?

답:

이전 질문과 동일한 방식으로 확인된다.

- 데이터에 포함된 두 특성의 최솟값 확인(반환값은 시리즈 객체)

In [14]:
desc.loc['min']

Chl-a        51.0
Discharge     9.0
Name: min, dtype: float64

- 방류량의 최솟값 확인

In [15]:
desc.loc['min', 'Discharge']

np.float64(9.0)

## 데이터프레임 기초 정보

특성은 수치형 특성과 범주형 특성으로 나뉘고, 수치형 특성은 이산형과 연속형으로 나눌 수 있다. 위 데이터의 경우, `학년`은 범주형 특성, 나머지는 모두 수치형 특성인데, `악력`을 제외한 수치형 특성들은 모두 이산형임을 알 수 있다.

- 데이터셋의 수치형 특성의 기본 통계 정보

In [8]:
sports_df.describe()

              학년         악력     윗몸일으키기         점수        순위
count  10.000000  10.000000  10.000000  10.000000  10.00000
mean    2.100000  38.880000  28.200000  13.000000   5.50000
std     0.875595   8.337306   6.828047   3.651484   3.02765
min     1.000000  26.000000  14.000000   7.000000   1.00000
25%     1.250000  34.775000  27.000000  10.250000   3.25000
50%     2.000000  37.800000  29.500000  13.500000   5.50000
75%     3.000000  45.600000  32.000000  15.750000   7.75000
max     3.000000  50.900000  37.000000  18.000000  10.00000

## 인덱싱

여기서는 불러들인 데이터셋을 이용해 앞에서 배운 행과 열 인덱싱을 간단하게 복습하기로 하자.

### 행 인덱싱

- `loc` 메서드

데이터프레임 sports_df를 생성할 때, 학생번호를 인덱스로 지정했던 것을 기억할 것이다. 따라서 `loc` 메서드를 이용하면 학생번호가 1인 학생의 체력 테스트 결과를 별도의 시리즈로 추출할 수 있다.

In [9]:
sports_df.loc[1]

학년         1.0
악력        40.2
윗몸일으키기    34.0
점수        15.0
순위         4.0
Name: 1, dtype: float64

- `iloc` 메서드

반면에, `iloc` 메서드를 사용하면 각 행에 자동으로 매겨진 정수 인덱스를 이용해 학생번호가 1인 학생의 정보를 동일하게 얻을 수 있다.

In [10]:
sports_df.iloc[0]

학년         1.0
악력        40.2
윗몸일으키기    34.0
점수        15.0
순위         4.0
Name: 1, dtype: float64

### 열 인덱싱

데이터프레임에서 악력에 대한 열을 추출하면
모든 학생의 악력에 대한 정보만을 담은
1차원 자료구조인 시리즈<font size='2'>Series</font>가 반환된다.

In [11]:
악력1D = sports_df['악력']
악력1D

학생번호
1     40.2
2     34.2
3     28.8
4     39.0
5     50.9
6     36.5
7     36.6
8     49.2
9     26.0
10    47.4
Name: 악력, dtype: float64

In [12]:
악력1D.ndim

1

반면에 아래와 같이 리스트를 사용하면 2차원 자료구조인 데이터프레임이 반환된다.

In [13]:
악력2D = sports_df[['악력']]
악력2D

        악력
학생번호
1     40.2
2     34.2
3     28.8
4     39.0
5     50.9
6     36.5
7     36.6
8     49.2
9     26.0
10    47.4

In [14]:
악력2D.ndim

2

`악력1D`와 `악력2D`는 내용면에서는 동일하며 거의 동일하게 활용될 수 있다.
하지만 여러 개의 특성을 지정하려면 반드시 리스트 형식으로 사용해야 한다.
예를 들어 아래 코드는 모든 학생에 대해 학년과 악력 정보를 함께 담은 데이터프레임을 가리킨다.

In [15]:
학년과악력 = sports_df[['학년', '악력']]
학년과악력

      학년    악력
학생번호
1      1  40.2
2      1  34.2
3      1  28.8
4      2  39.0
5      2  50.9
6      2  36.5
7      3  36.6
8      3  49.2
9      3  26.0
10     3  47.4

`loc`과 `iloc` 메서드를 이용해 열 인덱싱을 할 수도 있는데, 이때는 행 전체를 나타내는 `:`이 동반되어야 한다.

- loc 활용

In [16]:
악력1D = sports_df.loc[:, '악력']
악력1D

학생번호
1     40.2
2     34.2
3     28.8
4     39.0
5     50.9
6     36.5
7     36.6
8     49.2
9     26.0
10    47.4
Name: 악력, dtype: float64

In [17]:
악력2D = sports_df.loc[:, ['악력']]
악력2D

        악력
학생번호
1     40.2
2     34.2
3     28.8
4     39.0
5     50.9
6     36.5
7     36.6
8     49.2
9     26.0
10    47.4

In [18]:
학년과약력 = sports_df.loc[:, ['학년', '악력']]
학년과약력

      학년    악력
학생번호
1      1  40.2
2      1  34.2
3      1  28.8
4      2  39.0
5      2  50.9
6      2  36.5
7      3  36.6
8      3  49.2
9      3  26.0
10     3  47.4

- iloc 활용

자동으로 부여된 열 인덱스인 0, 1, 2, ..를 사용하면 된다.

In [19]:
악력1D = sports_df.iloc[:, 1]
악력1D

학생번호
1     40.2
2     34.2
3     28.8
4     39.0
5     50.9
6     36.5
7     36.6
8     49.2
9     26.0
10    47.4
Name: 악력, dtype: float64

In [20]:
악력2D = sports_df.iloc[:, 1:2]
악력2D

        악력
학생번호
1     40.2
2     34.2
3     28.8
4     39.0
5     50.9
6     36.5
7     36.6
8     49.2
9     26.0
10    47.4

In [21]:
학년과약력 = sports_df.iloc[:, :2]
학년과약력

      학년    악력
학생번호
1      1  40.2
2      1  34.2
3      1  28.8
4      2  39.0
5      2  50.9
6      2  36.5
7      3  36.6
8      3  49.2
9      3  26.0
10     3  47.4

## 연습문제

참고: [(연습) 데이터 다루기](https://colab.research.google.com/github/codingalzi/statsRev/blob/master/practices/practice-data_handling.ipynb)