# 판다스 데이터프레임

아래 엑셀 파일의 표<font size='2'>table</font> 형식으로 제공되는 
2차원 데이터를 효율적으로 처리하는 판다스 데이터프레임 자료형을 간단히 소개한다.
데이터프레임의 다양한 기능은 확률과 통계를 기초를 다루면서 하나씩 활용할 예정이다.

<div align="center">
    <img src="https://raw.githubusercontent.com/codingalzi/datapy/master/jupyter-book/images/excel-fruits.png" width="450">
</div>

**기본 설정**

`numpy`와 `pandas` 라이브러리를 각각 `np`와 `pd`로 불러온다.

In [1]:
import numpy as np
import pandas as pd

**데이터셋 저장소**

In [2]:
data_url = 'https://raw.githubusercontent.com/codingalzi/code-workout-datasci/refs/heads/master/data/'

## 데이터프레임 생성

**데이터프레임**<font size='2'>DataFrame</font>은 인덱스를 공유하는 여러 개의 시리즈가
결합된 2차원 데이터구조다.

**`pd.concat()` 함수 활용**

`pd.concat()` 함수는 여러 개의 시리즈 또는 데이터프레임을 묶어 하나의 데이터프레임을 생성한다.
묶는 방식은 축을 지정함으로써 결정되는데, 위 그림처럼 옆으로 묶으려면 열 단위로 추가한다는 뜻으로 `axis=1`을 설정하면 된다.
추가되는 각 열의 이름은 시리즈에 저장된 `name` 속성으로 지정된다.

In [3]:
series1 = pd.Series([4, 5, 6, 3, 1], name="Mango")
series2 = pd.Series([5, 4, 3, 0, 2], name="Apple")
series3 = pd.Series([2, 3, 5, 2, 7], name="Banana")

fruits1 = pd.concat([series1, series2, series3], axis=1)
fruits1

   Mango  Apple  Banana
0      4      5       2
1      5      4       3
2      6      3       5
3      3      0       2
4      1      2       7

자료형은 `pd.DataFrame`이다.

In [4]:
type(fruits1)

pandas.DataFrame

각 시리즈의 행 인덱스를 지정하지 않았기에
0부터 시작하는 정수 인덱스가 행 인덱스로 사용되며,
시리즈의 경우처럼 `RangeIndex` 객체가 데이터프레임의 `index` 속성에 저장된다.

In [5]:
fruits1.index

RangeIndex(start=0, stop=5, step=1)

**넘파이 2차원 어레이 활용**

넘파이 2차원 어레이를 이용하여 데이터프레임을 생성할 수 있다.
망고, 사과, 바나나 데이터를 담고 있는 아래 어레이를 이용하여 이전과
동일한 데이터프레임을 생성할 수 있다.

In [6]:
fruits_array = np.array([[4, 5, 2],
                         [5, 4, 3],
                         [6, 3, 5],
                         [3, 0, 2],
                         [1, 2, 7]])

데이터프레임 객체를 생성할 때 어레이를 생성자의 인자로 지정하면 된다.
또한 각 열의 이름을 담은 리스트를 `columns`의 키워드 인자로 지정한다.

In [7]:
fruits1= pd.DataFrame(fruits_array,
                     columns=['Mango', 'Apple', 'Banana'])
fruits1

   Mango  Apple  Banana
0      4      5       2
1      5      4       3
2      6      3       5
3      3      0       2
4      1      2       7

데이터프레임의 열별 이름을 **열 인덱스**라고 부르며,
`columns` 속성에 `Index` 객체로 저장된다.

In [8]:
fruits1.columns

Index(['Mango', 'Apple', 'Banana'], dtype='str')

시리즈 객체를 생성할 때처럼 행 인덱스를 지정하면서 데이터프레임 객체를 생성할 수 있다.
아래 코드는 A부터 E까지의 영어 대문자 알파벳을 행 인덱스로 지정한다.

In [9]:
fruits1= pd.DataFrame(fruits_array,
                     columns=['Mango', 'Apple', 'Banana'],
                     index=['A', 'B', 'C', 'D', 'E'])
fruits1

   Mango  Apple  Banana
A      4      5       2
B      5      4       3
C      6      3       5
D      3      0       2
E      1      2       7

행 인덱스를 별도로 지정하였기에 시리즈의 경우처럼
라벨 `Index` 객체가 행 인덱스 객체로 지정된다.

In [10]:
fruits1.index

Index(['A', 'B', 'C', 'D', 'E'], dtype='str')

**사전 활용**

열 이름을 키<font size='2'>key</font>로, 
리스트를 키의 값<font size='2'>value</font>으로 갖는 사전을 이용해 데이터프레임을 생성할 수 있다.
이때 모든 리스트의 길이가 동일해야 한다.

아래 코드에서 `fruits_dict`는 `Mango`, `Apple`, `Banana`를 키로,
각각의 키에 할당된 리스트를 갖는 사전을 정의한다.

In [11]:
fruits_dict = {'Mango': [4, 5, 6, 3, 1],
               'Apple': [5, 4, 3, 0, 2],
               'Banana': [2, 3, 5, 2, 7]}

위 사전 객체를 데이터프레임으로 변환하면 다음과 같으며,
사전에 사용된 키가 열 인덱스로 자동 지정된다.

In [12]:
fruits1 = pd.DataFrame(fruits_dict)
fruits1

   Mango  Apple  Banana
0      4      5       2
1      5      4       3
2      6      3       5
3      3      0       2
4      1      2       7

위 코드에서 행 인덱스를 별도로 지정하지 않았기에 이 경우에도
`RangeIndex` 인덱스 객체가 행 인덱스 객체로 지정된다.

In [13]:
fruits1.index

RangeIndex(start=0, stop=5, step=1)

## 데이터프레임 속성

데이터프레임은 행과 열 각각에 대해 `Index` 객체를 사용한다.
행에 대한 인덱스는 `index` 속성에, 열에 대한 인덱스는 `columns` 속성에 저장된다.

**`columns` 속성**

In [14]:
fruits1.columns

Index(['Mango', 'Apple', 'Banana'], dtype='str')

`columns` 속성을 이용하여 열의 순서를 변경할 수 있다.
아래 코드는 과일의 이름 순서대로 열을 지정한다.

In [19]:
fruits2 = pd.DataFrame(fruits1, columns=['Apple', 'Banana', 'Mango'])
fruits2

   Apple  Banana  Mango
0      5       2      4
1      4       3      5
2      3       5      6
3      0       2      3
4      2       7      1

**`index` 속성**

데이터프레임 `fruits1`의 행 인덱스는 자동 지정되었으므로 `RangeIndex` 객체가 사용되었다.

In [20]:
fruits1.index

RangeIndex(start=0, stop=5, step=1)

데이터프레임을 생성할 때 특정 인덱스를 사용하려면 `index` 속성을
리스트로 지정하면 된다.
단, 리스트의 길이가 행의 개수와 동일해야 한다.

In [21]:
fruits2 = pd.DataFrame(fruits_dict,
                       index=['하나', '둘', '셋', '넷', '다섯'])
fruits2

    Mango  Apple  Banana
하나      4      5       2
둘       5      4       3
셋       6      3       5
넷       3      0       2
다섯      1      2       7

`columns`와 `index` 속성을 동시에 지정할 수도 있다.

In [22]:
fruits3 = pd.DataFrame(fruits_array,
                       columns=['Mango', 'Apple', 'Banana'],
                       index=['A', 'B', 'C', 'D', 'E'])
fruits3

   Mango  Apple  Banana
A      4      5       2
B      5      4       3
C      6      3       5
D      3      0       2
E      1      2       7

**`name` 속성**

데이터프레임는 행 인덱스와 열 인덱스 객체 각각에 대해 `name` 속성을 지정할 수 있다.
아래 코드는 행과 열의 이름을 각각 `'순서'`와 `'과일'`로 지정한다.

In [23]:
fruits2.index.name = '순서'    # 행 이름 지정
fruits2.columns.name = '과일'  # 열 이름 지정
fruits2

과일  Mango  Apple  Banana
순서
하나      4      5       2
둘       5      4       3
셋       6      3       5
넷       3      0       2
다섯      1      2       7

행과 열의 이름이 지정한 대로 확인된다.

In [24]:
fruits2.index.name

'순서'

In [25]:
fruits2.columns.name

'과일'

**`values` 속성**

데이터프레임의 `values` 속성은 항목만으로 이루어진 2차원 어레이를 가리킨다.

In [26]:
fruits3.values

array([[4, 5, 2],
       [5, 4, 3],
       [6, 3, 5],
       [3, 0, 2],
       [1, 2, 7]])

## 데이터프레임 인덱싱

데이터프레임의 인덱싱과 슬라이싱은 모두 행과 열에 대해 서로 독립적으로 작동한다.
행과 열 각각에 대한 인덱싱과 슬라이싱의 작동방식은 시리즈의 인덱싱, 슬라이싱 방식과
매우 유사하다.
또한 넘파이 2차원 어레이의 경우처럼 행과 열에 대한 인덱싱, 슬라이싱을
조합할 수도 있다.

### 열 인덱싱

열 인덱싱은 세 가지 방식으로 지원된다.

- `[]` 활용
- `.loc[]` 활용
- `.iloc[]` 활용

데이터프레임 `fruits3`의 예를 들어 설명한다.

In [27]:
fruits3

   Mango  Apple  Banana
A      4      5       2
B      5      4       3
C      6      3       5
D      3      0       2
E      1      2       7

**`[]` 활용**

시리즈의 경우와는 다르게 대괄호만 사용하는 인덱싱은 열 라벨에 대해 실행된다.
예를 들어 아래 코드는 망고 열만 시리즈로 추출한다.

In [28]:
fruits3['Mango']

A    4
B    5
C    6
D    3
E    1
Name: Mango, dtype: int64

대괄호를 사용하지 않으면서 열의 이름을 마치 데이터프레임 객체의 속성인 것처럼 활용할 수 있다.
아래 코드는 `Banana` 열을 시리즈로 추출한다.

In [29]:
fruits3.Banana

A    2
B    3
C    5
D    2
E    7
Name: Banana, dtype: int64

**`.loc[]` 활용**

넘파이 2차원 어레이의 경우처럼 쉼표를 기준으로 행과, 열에 대한 인덱싱 또는 슬라이싱을 지정한다.
예를 들어 아래 코드는 사과 열만 시리즈로 추출하기 위해, 행에 대해서는 행 전체를 가리키는
슬라이싱 기호 (`:`)를 쉼표 왼쪽에 위치시켜야 한다.

In [30]:
fruits3.loc[:, 'Apple']

A    5
B    4
C    3
D    0
E    2
Name: Apple, dtype: int64

**`.iloc[]` 활용**

정수 인덱스로 열 인덱싱을 적용할 수 있다.
예를 들어, 사과는 1번 인덱스 열이기에 다음과 같이 추출한다.
행 전체 대상 슬라이싱이 여기서도 필요함에 주의한다.

In [31]:
fruits3.iloc[:, 1]

A    5
B    4
C    3
D    0
E    2
Name: Apple, dtype: int64

### 데이터프레임 열 추가/업데이트

열 라벨 인덱싱을 이용하여 새로운 특성을 추가할 수 있다.
아래 코드는 패선 프루트라는 특이한 이름의 과일 목록을 담은
`'Passion fruit'` 열을 새롭게 추가하면서
각 행의 값을 7로 지정한다.
넘파이 어레이에서 다룬 브로드캐스팅이 작동함에 주의한다.

In [32]:
fruits3['Passion fruit'] = 7
fruits3

   Mango  Apple  Banana  Passion fruit
A      4      5       2              7
B      5      4       3              7
C      6      3       5              7
D      3      0       2              7
E      1      2       7              7

동일한 방식으로 열의 항목을 업데이트 할 수도 있다.
아래 코드는 패선 푸르트 열의 각 행의 값을 5로 업데이트 한다.

In [33]:
fruits3['Passion fruit'] = 5
fruits3

   Mango  Apple  Banana  Passion fruit
A      4      5       2              5
B      5      4       3              5
C      6      3       5              5
D      3      0       2              5
E      1      2       7              5

행 전체의 길이와 동일한 리스트 또는 어레이를 이용하여 새로운 열을 추가하거나
기존에 있던 열의 항목을 업데이트 할 수 있다.
아래 코드는 포도 열을 추가하면서 길이가 5인 레인지 객체를 항목들의 값으로 지정하였다.

In [34]:
fruits3['Grape'] = range(10, 15)
fruits3

   Mango  Apple  Banana  Passion fruit  Grape
A      4      5       2              5     10
B      5      4       3              5     11
C      6      3       5              5     12
D      3      0       2              5     13
E      1      2       7              5     14

아래 코드는 패션 푸르트 열을 길이가 5인 리스트를 이용하여 업데이트 한다.

In [35]:
fruits3['Passion fruit'] = [5, 4, 3, 2, 1]
fruits3

   Mango  Apple  Banana  Passion fruit  Grape
A      4      5       2              5     10
B      5      4       3              4     11
C      6      3       5              3     12
D      3      0       2              2     13
E      1      2       7              1     14

참고로 팬션 푸르트 열을 인덱싱할 때 대괄호를 사용하는 지원되지 않는다.
이유는 대괄호를 사용하지 않는 인덱싱은 열의 이름이 파이썬이 
허용하는 변수 이름 작성 규칙을 따를 때만 가능하기 때문이다.

In [36]:
fruits3.Passion fruit

SyntaxError: invalid syntax (2891821880.py, line 1)

이런 경우엔 무조건 대괄호를 사용해야 한다.

In [37]:
fruits3['Passion fruit']

A    5
B    4
C    3
D    2
E    1
Name: Passion fruit, dtype: int64

### 행 인덱싱

행 인덱싱은 두 가지 방식으로 지원된다.

- `.loc[]` 활용
- `.iloc[]` 활용

즉, 대괄호만 사용하는 행 인덱싱은 지원되지 않는다.
데이터프레임 `fruits3`를 계속 활용하여 설명한다.

In [38]:
fruits3

   Mango  Apple  Banana  Passion fruit  Grape
A      4      5       2              5     10
B      5      4       3              4     11
C      6      3       5              3     12
D      3      0       2              2     13
E      1      2       7              1     14

**`.loc[]` 활용**

아래 코드는 `'A'` 라벨 행을 시리즈 객체로 추출한다.
생성된 시리즈의 행 인덱스는 데이터프레임의 열 인덱스가 사용된다.

In [39]:
fruits3.loc['A']

Mango             4
Apple             5
Banana            2
Passion fruit     5
Grape            10
Name: A, dtype: int64

**`.iloc[]` 활용**

정수 인덱스로 행 인덱싱을 적용할 수 있다.
예를 들어, `'C'` 라벨 행은 2번 인덱스 행이기에 다음과 같이 추출한다.

In [40]:
fruits3.iloc[2]

Mango             6
Apple             3
Banana            5
Passion fruit     3
Grape            12
Name: C, dtype: int64

### 팬시 인덱싱

열 인덱스 또는 행 인덱스로 구성된 리스트를 인덱싱에 활용하는 기법이
**팬시 인덱싱**<font size='2'>fancy indexing</font>이다.
이때, 라벨 또는 정수로만 구성된 리스트를 지정해야 하며,
결과는 지정된 순서의 열 또는 행으로 구성된 데이터프레임 객체다.

**열 팬시 인덱싱**

열 인덱싱처럼 세 가지 방식이 지원된다.
예를 들어 망고와 바나나 열로 구성된 데이터프레임을 생성해본다.

In [41]:
fruits3[['Mango', 'Banana', 'Passion fruit']]

   Mango  Banana  Passion fruit
A      4       2              5
B      5       3              4
C      6       5              3
D      3       2              2
E      1       7              1

In [42]:
fruits3.loc[:, ['Mango', 'Banana', 'Passion fruit']]

   Mango  Banana  Passion fruit
A      4       2              5
B      5       3              4
C      6       5              3
D      3       2              2
E      1       7              1

In [43]:
fruits3.iloc[:, [0, 2, 3]]

   Mango  Banana  Passion fruit
A      4       2              5
B      5       3              4
C      6       5              3
D      3       2              2
E      1       7              1

길이가 1인 인덱스 리스트를 사용해도 결과는 시리즈가 아닌 데이터프레임이다.

In [44]:
fruits3[['Apple']]

   Apple
A      5
B      4
C      3
D      0
E      2

In [45]:
type(fruits3[['Apple']])

pandas.DataFrame

일반 인덱싱의 결과는 시리즈임에 주의한다.

In [46]:
fruits3['Apple']

A    5
B    4
C    3
D    0
E    2
Name: Apple, dtype: int64

In [47]:
type(fruits3['Apple'])

pandas.Series

**행 팬시 인덱싱**

행 인덱싱처럼 두 가지 방식이 지원된다.
예를 들어 `'B'`, `'D'`, `'E'` 세 라벨 인덱스의 행으로 구성된 데이터프레임을 생성해본다.

In [48]:
fruits3.loc[['B', 'D', 'E']]

   Mango  Apple  Banana  Passion fruit  Grape
B      5      4       3              4     11
D      3      0       2              2     13
E      1      2       7              1     14

In [49]:
fruits3.iloc[[1, 3, 4]]

   Mango  Apple  Banana  Passion fruit  Grape
B      5      4       3              4     11
D      3      0       2              2     13
E      1      2       7              1     14

길이가 1인 인덱스 리스트를 사용해도 결과는 시리즈가 아닌 데이터프레임이다.

In [50]:
fruits3.loc[['A']]

   Mango  Apple  Banana  Passion fruit  Grape
A      4      5       2              5     10

In [51]:
fruits3.iloc[[0]]

   Mango  Apple  Banana  Passion fruit  Grape
A      4      5       2              5     10

## 데이터프레임 슬라이싱

`loc()` 과 `iloc()` 함수를 행과 열에 동시에 적용할 수 있으며,
넘파이 2차원 어레이에 대한 인덱싱/슬라이싱이 작동하는 방식과 거의 동일하다.
설명을 위해 계속해서 `fruits3`가 가리키는 데이터프레임을 이용한다.

In [52]:
fruits3

   Mango  Apple  Banana  Passion fruit  Grape
A      4      5       2              5     10
B      5      4       3              4     11
C      6      3       5              3     12
D      3      0       2              2     13
E      1      2       7              1     14

### 열 슬라이싱

열에 대해서만 슬라이싱을 적용하려면 행을 전체로 지정한다.
아래 코드는 전체 행을 대상으로 2번 인덱스열 이전까지 추출한다.

In [53]:
fruits3.iloc[:, :2]

   Mango  Apple
A      4      5
B      5      4
C      6      3
D      3      0
E      1      2

정수 인덱스가 아닌 열 라벨을 이용한 슬라이싱은 `loc()`함수를 써야하고, 지정한 구간의 끝도 포함됨에 유의한다.

In [54]:
fruits3.loc[:, :'Banana']

   Mango  Apple  Banana
A      4      5       2
B      5      4       3
C      6      3       5
D      3      0       2
E      1      2       7

### 행 슬라이싱

행에 대해서만 슬라이싱을 적용하려면 열을 전체로 지정한다.
아래 코드는 2번 인덱스 행부터 모두 가져온다.

In [55]:
fruits3.iloc[2:, :]

   Mango  Apple  Banana  Passion fruit  Grape
C      6      3       5              3     12
D      3      0       2              2     13
E      1      2       7              1     14

열 슬라이싱은 지정하지 않아도 된다.

In [56]:
fruits3.iloc[2:]

   Mango  Apple  Banana  Passion fruit  Grape
C      6      3       5              3     12
D      3      0       2              2     13
E      1      2       7              1     14

행과 열 슬라이싱을 동시에 진행할 수도 있다.
아래 코드는 2번 인덱스 행부터의 모든 행을 대상으로 3번 인덱스 열 이전까지의 항목만 추출한다.

In [57]:
fruits3.iloc[2:, :3]

   Mango  Apple  Banana
C      6      3       5
D      3      0       2
E      1      2       7

**스텝 활용**

스텝<font size='2'>step</font>도 사용할 수 있다.
아래 코드는 짝수 인덱스 행에 속한 항목 중에서 홀수 인덱스 열의 항목만 추출한다.

In [58]:
fruits3.iloc[::2, 1::2]

   Apple  Passion fruit
A      5              5
C      3              3
E      2              1

### 인덱싱과 슬라이싱의 조합

인덱싱과 슬라이싱의 어떤 조합도 행과 열에 대해 적용할 수 있다.

아래 코드는 `'C'`라벨 행의 `'Apple'`과 `'Grape'` 열의 항목을 별도의 시리즈로 추출한다.

In [59]:
fruits3.loc['C', ['Apple', 'Grape']]

Apple     3
Grape    12
Name: C, dtype: int64

아래 코드는 `'C'` 라벨 행까지의 모든 행에서 `'Banana'` 열의 항목을 시리즈로 추출한다.

In [60]:
fruits3.loc[:'C', 'Banana']

A    2
B    3
C    5
Name: Banana, dtype: int64

아래 코드는 2번 인덱스 행의 1번, 2번 인덱스 열의 항목을 시리즈로 추출한다.

In [61]:
fruits3.iloc[2, [1, 2]]

Apple     3
Banana    5
Name: C, dtype: int64

아래 코드는 1번, 2번 인덱스 행의 3번, 0번, 1번 인덱스 열의 항목을 별도의 데이터프레임으로 추출한다.

In [62]:
fruits3.iloc[[1, 2], [3, 0, 1]]

   Passion fruit  Mango  Apple
B              4      5      4
C              3      6      3

아래 코드는 `'D'` 라벨 행까지의 모든 행에서 `'Banana'` 열부터 이후의 모든 열의 항목을 데이터프레임으로 추출한다.

In [63]:
fruits3.loc[:'D', 'Banana':]

   Banana  Passion fruit  Grape
A       2              5     10
B       3              4     11
C       5              3     12
D       2              2     13

## 연습문제

**예제 1**

(1) 아래 사전으로 데이터프레임 `df1`을 생성하시오.

In [45]:
abcd_dict = {"A": 1.0,
             "B": pd.Series(1, index=list(range(4)), dtype="float32"),
             "C": np.array([3] * 4, dtype="int32"),
             "D": ["test", "train", "test", "train"]}

답:

동일한 길이의 리스트를 값으로 갖는 사전이므로, 데이터프레임 생성에서 키가 열 인덱스로 사용된다.

In [46]:
df1 = pd.DataFrame(abcd_dict)
df1

     A    B  C      D
0  1.0  1.0  3   test
1  1.0  1.0  3  train
2  1.0  1.0  3   test
3  1.0  1.0  3  train

(2) 데이터프레임 `df1`의 열별 자료형을 확인하시오.

답:

열별 자료형은 `dtypes` 속성으로 확인할 수 있다.

In [47]:
df1.dtypes

A    float64
B    float32
C      int32
D     object
dtype: object

**예제 2**

`pd.date_range()` 함수는 시간으로 구성된 인덱스 자료형을 생성한다.
아래 코드에서 함수 호출에 사용된 키워드 인자의 의미는 다음과 같다.

- `start="20250101`: 2025년 1월 1일부터 시작
- `periods=6`: 첫째 인자로 지정된 시간부터 6 개의 시간 데이터 샘플 생성
- `freq="D"`: 시간 데이터 샘플을 일(Day) 단위로 생성

In [48]:
dates = pd.date_range(start="20250101", periods=6, freq="D")
dates

DatetimeIndex(['2025-01-01', '2025-01-02', '2025-01-03', '2025-01-04',
               '2025-01-05', '2025-01-06'],
              dtype='datetime64[ns]', freq='D')

아래 코드는 (6, 4) 모양의 데이터프레임을 생성한다.

- 행 인덱스: 앞서 선언한 `dates` 변수가 가리키는 `DatetimeIndex` 객체를 이용
- 항목: `np.random.randn()` 함수를 이용하여 무작위 부동소수점으로 생성된 2차원 어레이 이용
- 열 인덱스: `['A', 'B', 'C', 'D']` 지정

In [49]:
np.random.seed(0) # 무작위 생성 함수의 시드 지정.

df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list("ABCD"))
df

                   A         B         C         D
2025-01-01  1.764052  0.400157  0.978738  2.240893
2025-01-02  1.867558 -0.977278  0.950088 -0.151357
2025-01-03 -0.103219  0.410599  0.144044  1.454274
2025-01-04  0.761038  0.121675  0.443863  0.333674
2025-01-05  1.494079 -0.205158  0.313068 -0.854096
2025-01-06 -2.552990  0.653619  0.864436 -0.742165

(1) `'A'` 열만을 추출하여 시리즈를 생성하시오.

답:

열 라벨을 이용한 인덱싱을 적용한다.

In [50]:
df["A"]

2025-01-01    1.764052
2025-01-02    1.867558
2025-01-03   -0.103219
2025-01-04    0.761038
2025-01-05    1.494079
2025-01-06   -2.552990
Freq: D, Name: A, dtype: float64

또는 열 라벨을 객체의 속성처럼 이용하는 방식도 가능하다. 단, 열 라벨의 이름이 공백을 포함하지 않아야 한다.

In [51]:
df.A

2025-01-01    1.764052
2025-01-02    1.867558
2025-01-03   -0.103219
2025-01-04    0.761038
2025-01-05    1.494079
2025-01-06   -2.552990
Freq: D, Name: A, dtype: float64

(2) 0번 행부터 2번 행까지만 포함하는 데이터프레임을 생성하시오.

답:

정수 인덱스를 활용한 슬라이싱을 적용한다.

In [52]:
df.iloc[0:3]

                   A         B         C         D
2025-01-01  1.764052  0.400157  0.978738  2.240893
2025-01-02  1.867558 -0.977278  0.950088 -0.151357
2025-01-03 -0.103219  0.410599  0.144044  1.454274

또는 인덱스 라벨을 활용하여 슬라이싱을 진행할 수도 있다.
위치 인덱스 방식과는 달리 구간의 마지막 라벨로 포함된다.

In [53]:
df["2025-01-01":"2025-01-03"]

                   A         B         C         D
2025-01-01  1.764052  0.400157  0.978738  2.240893
2025-01-02  1.867558 -0.977278  0.950088 -0.151357
2025-01-03 -0.103219  0.410599  0.144044  1.454274

날짜표기에 사용된 대쉬 기호는 생략해도 된다.

In [54]:
df["20250101":"20250103"]

                   A         B         C         D
2025-01-01  1.764052  0.400157  0.978738  2.240893
2025-01-02  1.867558 -0.977278  0.950088 -0.151357
2025-01-03 -0.103219  0.410599  0.144044  1.454274

(3) 첫번째 날짜, 즉 2025년 1월 1일의 데이터를 확인하는 한 줄 표현식을 작성하시오.
단, `loc[]` 객체와 `dates` 변수를 이용해야 한다.

답:

In [55]:
df.loc[dates[0]]

A    1.764052
B    0.400157
C    0.978738
D    2.240893
Name: 2025-01-01 00:00:00, dtype: float64

(4) `loc[]` 객체를 이용해 `'A'`와 `'B'` 두 열만 추출하는 한 줄 표현식을 작성하시오.

답:

In [56]:
df.loc[:, ["A", "B"]]

                   A         B
2025-01-01  1.764052  0.400157
2025-01-02  1.867558 -0.977278
2025-01-03 -0.103219  0.410599
2025-01-04  0.761038  0.121675
2025-01-05  1.494079 -0.205158
2025-01-06 -2.552990  0.653619

(5) `loc[]` 객체를 이용하여 2025년 1월 2일부터 1월 4일까지를 대상으로 `A`, `B` 두 열만 추출하는 한 줄 표현식을 작성하시오.

답:

In [57]:
df.loc["20250102":"20250104", ["A", "B"]]

                   A         B
2025-01-02  1.867558 -0.977278
2025-01-03 -0.103219  0.410599
2025-01-04  0.761038  0.121675

(6) `loc[]` 객체를 이용하여 2025년 1월 2일의 `A`, `B` 두 열만 추출하는 한 줄 표현식을 작성하시오.

답:

In [58]:
df.loc["20250102", ["A", "B"]]

A    1.867558
B   -0.977278
Name: 2025-01-02 00:00:00, dtype: float64

(7) `loc[]` 객체와 `dates` 변수를 이용해 2025년 1월 1일의 `A` 열만 추출하는 한 줄 표현식을 작성하시오.

답:

In [59]:
df.loc[dates[0], "A"]

1.764052345967664

(8) `iloc[]` 객체를 이용해 3번 행만 추출하는 한 줄 표현식을 작성하시오.

답:

In [60]:
df.iloc[3]

A    0.761038
B    0.121675
C    0.443863
D    0.333674
Name: 2025-01-04 00:00:00, dtype: float64

(9)  `iloc[]` 객체를 이용해 3번부터 4번 인덱스 행을 대상으로 0번, 1번 인덱스의 열만 추출하는 한 줄 표현식을 작성하시오.

답:

In [61]:
df.iloc[3:5, 0:2]

                   A         B
2025-01-04  0.761038  0.121675
2025-01-05  1.494079 -0.205158

(10) 아래 두 리스트에 포함된 행과 열만 순서대로 추출하는 한 줄 표현식을 작성하시오.
단, `iloc[]` 객체와 팬시 인덱싱을 활용한다.

- 행: `[1, 2, 4]`
- 열: `[0, 2, 3, 1]`

답:

In [62]:
df.iloc[[1, 2, 4], [0, 2, 3, 1]]

                   A         C         D         B
2025-01-02  1.867558  0.950088 -0.151357 -0.977278
2025-01-03 -0.103219  0.144044  1.454274  0.410599
2025-01-05  1.494079  0.313068 -0.854096 -0.205158

(11) `iloc[]` 객체를 이용해 홀수 행만 추출하는 한 줄 표현식을 작성하시오.

답:

In [63]:
df.iloc[1::2, :]

                   A         B         C         D
2025-01-02  1.867558 -0.977278  0.950088 -0.151357
2025-01-04  0.761038  0.121675  0.443863  0.333674
2025-01-06 -2.552990  0.653619  0.864436 -0.742165

1번 축(행) 정보는 무시해도 된다.

In [64]:
df.iloc[1::2]

                   A         B         C         D
2025-01-02  1.867558 -0.977278  0.950088 -0.151357
2025-01-04  0.761038  0.121675  0.443863  0.333674
2025-01-06 -2.552990  0.653619  0.864436 -0.742165

(12) `iloc[]` 객체를 이용해 1번, 2번 열만 추출하는 한 줄 표현식을 작성하시오.

답:

0번 축에 대해서는 모든 행을 가져오라는 슬라이싱을 명시해야 한다.

In [65]:
df.iloc[:, 1:3]

                   B         C
2025-01-01  0.400157  0.978738
2025-01-02 -0.977278  0.950088
2025-01-03  0.410599  0.144044
2025-01-04  0.121675  0.443863
2025-01-05 -0.205158  0.313068
2025-01-06  0.653619  0.864436